/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoIndexRouteImport } from './routes/historico.index'
import { Route as HistoricoIdRouteImport } from './routes/historico.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIndexRoute = HistoricoIndexRouteImport.update({
  id: '/historico/',
  path: '/historico/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIdRoute = HistoricoIdRouteImport.update({
  id: '/historico/$id',
  path: '/historico/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico/$id': typeof HistoricoIdRoute
  '/historico/': typeof HistoricoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico/$id': typeof HistoricoIdRoute
  '/historico': typeof HistoricoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico/$id': typeof HistoricoIdRoute
  '/historico/': typeof HistoricoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historico/$id' | '/historico/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historico/$id' | '/historico'
  id: '__root__' | '/' | '/historico/$id' | '/historico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoIdRoute: typeof HistoricoIdRoute
  HistoricoIndexRoute: typeof HistoricoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/': {
      id: '/historico/'
      path: '/historico'
      fullPath: '/historico/'
      preLoaderRoute: typeof HistoricoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$id': {
      id: '/historico/$id'
      path: '/historico/$id'
      fullPath: '/historico/$id'
      preLoaderRoute: typeof HistoricoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoIdRoute: HistoricoIdRoute,
  HistoricoIndexRoute: HistoricoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
